services:
  app:
    build: .
    container_name: job_manager_app
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: php index.php

  db:
    image: mysql:8.0
    container_name: job_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobboard
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
